#image: docker:git
#services:
#  - docker:dind

variables:
  DOCKER_REGISTRY_USER: ${DOCKER_REGISTRY_USER}
  DOCKER_REGISTRY_PASS: ${DOCKER_REGISTRY_PASS}
  DOCKER_IMAGE_TAG: brk3/guestbook:${CI_COMMIT_SHORT_SHA}

build-job:
  stage: build
  script:
    - cd guestbook-go
    - docker build -t $DOCKER_IMAGE_TAG .

push-job:
  stage: build
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p DOCKER_REGISTRY_PASS
    - docker push $DOCKER_IMAGE_TAG

deploy:
 image:
   name: bitnami/kubectl:latest
   entrypoint: [""]
 script:
   - kubectl config get-contexts
   - kubectl config use-context mygroup1371/myproject:pbourke
   - kubectl get pods