#image: docker:git
#services:
#  - docker:dind

variables:
  CI_REGISTRY_USER: ${CI_REGISTRY_USER}
  CI_REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}
  CI_IMAGE_TAG: brk3/guestbook:${CI_COMMIT_SHORT_SHA}
  CI_REGISTRY: "https://index.docker.io/v1/"

#build-job:
#  stage: build
#  script:
#    - cd guestbook-go
#    - docker build -t $DOCKER_IMAGE_TAG .

#push-job:
#  stage: build
#  script:
#    - docker login -u $DOCKER_REGISTRY_USER -p DOCKER_REGISTRY_PASS
#    - docker push $DOCKER_IMAGE_TAG

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "guestbook-go"
      --dockerfile "guestbook-go/Dockerfile"
      --destination "${CI_IMAGE_TAG}"

deploy:
 image:
   name: bitnami/kubectl:latest
   entrypoint: [""]
 script:
   - kubectl config get-contexts
   - kubectl config use-context mygroup1371/myproject:pbourke
   - sed -i "s|k8s.gcr.io/guestbook:v3|${CI_IMAGE_TAG}|" guestbook-go/guestbook-controller.yaml
   - kubectl apply -f guestbook-go/ -n pbourke