image: docker:git
services:
  - docker:dind

build-job:
  stage: build
  script:
    - cd guestbook-go
    #- REGISTRY=brk3/guestbook-go make build
    - docker build -t brk3/guestbook:${VERSION} .

push-job:
  stage: build
  script:
    - echo "todo..."
    #- REGISTRY=brk3/guestbook-go make push
