apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-{{ .Values.targetRole }}
  labels:
    app: guestbook
    role: {{ .Values.targetRole }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        role: {{ .Values.targetRole }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: guestbook
        ports:
        - containerPort: 3000
          name: http-server
          protocol: TCP
        resources: {}
