apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-{{ .Values.name }}
  labels:
    app: guestbook-{{ .Values.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: guestbook-{{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: guestbook
        ports:
        - containerPort: 3000
          name: http-server
          protocol: TCP
        resources: {}
