apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: guestbook-{{ .Values.name }}
  namespace: guestbook-{{ .Values.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: guestbook.{{ .Values.ingressIP }}.nip.io
    http:
      paths:
      - backend:
          service:
            name: guestbook-{{ .Values.name }}
            port:
              number: 3000
        path: /(.*)
        pathType: Exact
