apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: replica
  name: redis-replica
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 6379
    protocol: TCP
    targetPort: redis-server
  selector:
    app: redis
    role: replica
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
