apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: replica
  name: redis-replica
spec:
  replicas: 2
  selector:
    app: redis
    role: replica
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        role: replica
    spec:
      containers:
      - image: k8s.gcr.io/redis-slave:v2
        imagePullPolicy: IfNotPresent
        name: redis-replica
        ports:
        - containerPort: 6379
          name: redis-server
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
