# Default values for guestbook-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: brk3/guestbook:eb1f9612
ingressIP: x.x.x.x
# Allowable values: rolling, bluegreen, canary
updateStrategy: rolling
